### ISSUE TITLE
How to implement this grapher in html page for wagon wheel?

### ISSUE THREAD

**Issue by vyvanand** [rcbdev/grapher#1]
Hello,

```
I included grapher.js in my html page. How can I pass value from html page and get the output in browser?
```

Thanks
Brad

**Comment by Mittineague** [comment]
Some example code at http://www.sitepoint.com/forums/showthread.php?1188758-Draw-wagon-wheel-chart-using-jquery-for-cricket&p=5621657&viewfull=1#post5621657
